# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 235bb4d1d5a36097e935060ac631f471cd9645a9a6ff5d63aeb8b945e0707207a29767a1648bde825476091510c7cbb2fce0e4f51bb2a082e7f84180d2a676f8

test:
  secret_key_base: 5eacc7aa69548975104d0863c3d7f980aab5cd3473a6939d68bcf482edf8abeca5f8131abca89cfd46fd8dc0dc097b90587addfd8e0e4778fec4d5e718470578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
